//! Build script: compiles `data/raids.toml` into optimised static lookup tables.
//!
//! Generates `$OUT_DIR/raid_data_generated.rs` which is `include!`d by `src/raid_data.rs`.
//! The generated file contains:
//!   - A sorted `&[(&str, &str)]` for NPC name → raid name lookup (binary search)
//!   - A sorted `&[(&str, &str)]` for boss name → raid name lookup (binary search)
//!   - A `&[(&str, usize)]` for raid name → encounter count
//!   - A `&[&str]` for all known boss names
//!   - A `&[(&str, &str)]` for zone aliases
//!   - A `&[&str]` for overworld zones

use serde::Deserialize;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

#[derive(Deserialize)]
struct RaidDb {
    zone_aliases: BTreeMap<String, String>,
    overworld: Overworld,
    raid: Vec<Raid>,
}

#[derive(Deserialize)]
struct Overworld {
    zones: Vec<String>,
}

#[derive(Deserialize)]
struct Raid {
    name: String,
    /// If true, this is a 5-man dungeon rather than a raid instance.
    #[serde(default)]
    dungeon: bool,
    encounter_count: usize,
    #[allow(dead_code)] // Parsed for future use (encounter-level detail)
    #[serde(default)]
    encounters: Vec<String>,
    #[serde(default)]
    bosses: Vec<String>,
    #[serde(default)]
    trash: Vec<String>,
}

#[allow(clippy::too_many_lines)] // Code-generation — linear sequence of write! calls
fn main() {
    println!("cargo:rerun-if-changed=data/raids.toml");

    let toml_str = fs::read_to_string("data/raids.toml").expect("failed to read data/raids.toml");
    let db: RaidDb = toml::from_str(&toml_str).expect("failed to parse data/raids.toml");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("raid_data_generated.rs");
    let mut out = fs::File::create(&out_path).expect("failed to create output file");

    // Collect all NPC→raid mappings (bosses + trash), sorted by lowercase name
    let mut npc_to_raid: Vec<(String, String)> = Vec::new();
    let mut boss_to_raid: Vec<(String, String)> = Vec::new();
    let mut all_bosses: Vec<String> = Vec::new();
    let mut raid_encounter_counts: Vec<(String, usize)> = Vec::new();

    for raid in &db.raid {
        let raid_lower = raid.name.to_lowercase();
        raid_encounter_counts.push((raid_lower.clone(), raid.encounter_count));

        for boss in &raid.bosses {
            let lower = boss.to_lowercase();
            npc_to_raid.push((lower.clone(), raid_lower.clone()));
            boss_to_raid.push((lower.clone(), raid_lower.clone()));
            all_bosses.push(lower);
        }
        for trash in &raid.trash {
            let lower = trash.to_lowercase();
            npc_to_raid.push((lower, raid_lower.clone()));
        }
    }

    npc_to_raid.sort();
    npc_to_raid.dedup_by(|a, b| a.0 == b.0);
    boss_to_raid.sort();
    boss_to_raid.dedup_by(|a, b| a.0 == b.0);
    all_bosses.sort();
    all_bosses.dedup();
    raid_encounter_counts.sort();

    let mut zone_aliases: Vec<(String, String)> = db
        .zone_aliases
        .iter()
        .map(|(k, v)| (k.to_lowercase(), v.to_lowercase()))
        .collect();
    zone_aliases.sort();

    let mut overworld: Vec<String> = db
        .overworld
        .zones
        .iter()
        .map(|z| z.to_lowercase())
        .collect();
    overworld.sort();

    // Write the generated Rust source
    writeln!(out, "// @generated by build.rs from data/raids.toml").unwrap();
    writeln!(out, "// Do not edit manually.").unwrap();
    writeln!(out).unwrap();

    // NPC name → raid name (sorted for binary search)
    writeln!(
        out,
        "/// All raid NPCs (bosses + trash) → canonical raid name, sorted for binary search."
    )
    .unwrap();
    writeln!(out, "pub(crate) static NPC_TO_RAID: &[(&str, &str)] = &[").unwrap();
    for (npc, raid) in &npc_to_raid {
        writeln!(out, "    ({}, {}),", quote(npc), quote(raid)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Boss name → raid name (sorted for binary search)
    writeln!(
        out,
        "/// Boss NPCs only → canonical raid name, sorted for binary search."
    )
    .unwrap();
    writeln!(out, "pub(crate) static BOSS_TO_RAID: &[(&str, &str)] = &[").unwrap();
    for (boss, raid) in &boss_to_raid {
        writeln!(out, "    ({}, {}),", quote(boss), quote(raid)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // All boss names (sorted for binary search)
    writeln!(
        out,
        "/// All known boss names (lowercased, sorted) for O(log n) lookup."
    )
    .unwrap();
    writeln!(out, "pub(crate) static ALL_BOSSES: &[&str] = &[").unwrap();
    for boss in &all_bosses {
        writeln!(out, "    {},", quote(boss)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Raid encounter counts (sorted)
    writeln!(
        out,
        "/// Raid name → encounter count, sorted for binary search."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static RAID_ENCOUNTER_COUNTS: &[(&str, usize)] = &["
    )
    .unwrap();
    for (raid, count) in &raid_encounter_counts {
        writeln!(out, "    ({}, {count}),", quote(raid)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Zone aliases (sorted)
    writeln!(
        out,
        "/// Zone name aliases: addon-reported name → canonical raid name."
    )
    .unwrap();
    writeln!(out, "pub(crate) static ZONE_ALIASES: &[(&str, &str)] = &[").unwrap();
    for (alias, canonical) in &zone_aliases {
        writeln!(out, "    ({}, {}),", quote(alias), quote(canonical)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Overworld zones (sorted)
    writeln!(
        out,
        "/// Non-raid overworld zones that should never be treated as raid instances."
    )
    .unwrap();
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "pub(crate) static OVERWORLD_ZONES: &[&str] = &[").unwrap();
    for z in &overworld {
        writeln!(out, "    {},", quote(z)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // All instance names (sorted) — includes both raids and dungeons
    writeln!(
        out,
        "/// All canonical instance zone names (lowercased, sorted) for O(log n) lookup."
    )
    .unwrap();
    writeln!(out, "pub(crate) static ALL_RAID_ZONES: &[&str] = &[").unwrap();
    let mut raid_names: Vec<String> = db.raid.iter().map(|r| r.name.to_lowercase()).collect();
    raid_names.sort();
    for name in &raid_names {
        writeln!(out, "    {},", quote(name)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Dungeon-only zones (sorted) — subset of ALL_RAID_ZONES where dungeon = true
    writeln!(
        out,
        "/// Dungeon zone names (5-man instances, sorted) for O(log n) lookup."
    )
    .unwrap();
    writeln!(out, "pub(crate) static DUNGEON_ZONES: &[&str] = &[").unwrap();
    let mut dungeon_names: Vec<String> = db
        .raid
        .iter()
        .filter(|r| r.dungeon)
        .map(|r| r.name.to_lowercase())
        .collect();
    dungeon_names.sort();
    for name in &dungeon_names {
        writeln!(out, "    {},", quote(name)).unwrap();
    }
    writeln!(out, "];").unwrap();

    eprintln!(
        "raid_data: {} NPCs ({} bosses, {} trash), {} raids, {} zone aliases",
        npc_to_raid.len(),
        boss_to_raid.len(),
        npc_to_raid.len() - boss_to_raid.len(),
        db.raid.len(),
        zone_aliases.len()
    );
}

/// Quote a string as a Rust string literal.
fn quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}
