//! Build script: compiles `data/raids.toml` and `data/consumables.toml` into
//! optimised static lookup tables.
//!
//! Generates:
//!   - `$OUT_DIR/raid_data_generated.rs` (included by `src/raid_data.rs`)
//!   - `$OUT_DIR/consumable_data_generated.rs` (included by `src/consumable_data.rs`)

use serde::Deserialize;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

#[derive(Deserialize)]
struct RaidDb {
    zone_aliases: BTreeMap<String, String>,
    overworld: Overworld,
    raid: Vec<Raid>,
}

#[derive(Deserialize)]
struct Overworld {
    zones: Vec<String>,
}

#[derive(Deserialize)]
struct Raid {
    name: String,
    /// If true, this is a 5-man dungeon rather than a raid instance.
    #[serde(default)]
    dungeon: bool,
    encounter_count: usize,
    #[allow(dead_code)] // Parsed for future use (encounter-level detail)
    #[serde(default)]
    encounters: Vec<String>,
    /// Multi-boss encounter groups: maps a group name to its constituent bosses.
    /// Used to rename individual boss encounters (e.g. "Lord Kri" → "The Bug Family").
    #[serde(default)]
    encounter_groups: Vec<EncounterGroup>,
    #[serde(default)]
    bosses: Vec<String>,
    #[serde(default)]
    trash: Vec<String>,
}

#[derive(Deserialize)]
struct EncounterGroup {
    name: String,
    bosses: Vec<String>,
}

fn main() {
    generate_raid_data();
    generate_consumable_data();
}

// ── Raid Data Codegen ───────────────────────────────────────────────────────

#[allow(clippy::too_many_lines)] // Code-generation — linear sequence of write! calls
fn generate_raid_data() {
    println!("cargo:rerun-if-changed=data/raids.toml");

    let toml_str = fs::read_to_string("data/raids.toml").expect("failed to read data/raids.toml");
    let db: RaidDb = toml::from_str(&toml_str).expect("failed to parse data/raids.toml");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("raid_data_generated.rs");
    let mut out = fs::File::create(&out_path).expect("failed to create output file");

    // Collect all NPC→raid mappings (bosses + trash), sorted by lowercase name
    let mut npc_to_raid: Vec<(String, String)> = Vec::new();
    let mut boss_to_raid: Vec<(String, String)> = Vec::new();
    let mut all_bosses: Vec<String> = Vec::new();
    let mut raid_encounter_counts: Vec<(String, usize)> = Vec::new();

    for raid in &db.raid {
        let raid_lower = raid.name.to_lowercase();
        raid_encounter_counts.push((raid_lower.clone(), raid.encounter_count));

        for boss in &raid.bosses {
            let lower = boss.to_lowercase();
            npc_to_raid.push((lower.clone(), raid_lower.clone()));
            boss_to_raid.push((lower.clone(), raid_lower.clone()));
            all_bosses.push(lower);
        }
        for trash in &raid.trash {
            let lower = trash.to_lowercase();
            npc_to_raid.push((lower, raid_lower.clone()));
        }
    }

    // Collect boss → encounter group mappings for multi-boss fights
    let mut boss_to_encounter: Vec<(String, String)> = Vec::new();
    for raid in &db.raid {
        for group in &raid.encounter_groups {
            for boss in &group.bosses {
                boss_to_encounter.push((boss.to_lowercase(), group.name.clone()));
            }
        }
    }
    boss_to_encounter.sort();

    npc_to_raid.sort();
    npc_to_raid.dedup_by(|a, b| a.0 == b.0);
    boss_to_raid.sort();
    boss_to_raid.dedup_by(|a, b| a.0 == b.0);
    all_bosses.sort();
    all_bosses.dedup();
    raid_encounter_counts.sort();

    let mut zone_aliases: Vec<(String, String)> = db
        .zone_aliases
        .iter()
        .map(|(k, v)| (k.to_lowercase(), v.to_lowercase()))
        .collect();
    zone_aliases.sort();

    let mut overworld: Vec<String> = db
        .overworld
        .zones
        .iter()
        .map(|z| z.to_lowercase())
        .collect();
    overworld.sort();

    // Write the generated Rust source
    writeln!(out, "// @generated by build.rs from data/raids.toml").unwrap();
    writeln!(out, "// Do not edit manually.").unwrap();
    writeln!(out).unwrap();

    // NPC name → raid name (sorted for binary search)
    writeln!(
        out,
        "/// All raid NPCs (bosses + trash) → canonical raid name, sorted for binary search."
    )
    .unwrap();
    writeln!(out, "pub(crate) static NPC_TO_RAID: &[(&str, &str)] = &[").unwrap();
    for (npc, raid) in &npc_to_raid {
        writeln!(out, "    ({}, {}),", quote(npc), quote(raid)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Boss name → raid name (sorted for binary search)
    writeln!(
        out,
        "/// Boss NPCs only → canonical raid name, sorted for binary search."
    )
    .unwrap();
    writeln!(out, "pub(crate) static BOSS_TO_RAID: &[(&str, &str)] = &[").unwrap();
    for (boss, raid) in &boss_to_raid {
        writeln!(out, "    ({}, {}),", quote(boss), quote(raid)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // All boss names (sorted for binary search)
    writeln!(
        out,
        "/// All known boss names (lowercased, sorted) for O(log n) lookup."
    )
    .unwrap();
    writeln!(out, "pub(crate) static ALL_BOSSES: &[&str] = &[").unwrap();
    for boss in &all_bosses {
        writeln!(out, "    {},", quote(boss)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Boss name → encounter group name (for multi-boss fights, sorted for binary search)
    writeln!(
        out,
        "/// Individual boss NPC → encounter group name for multi-boss fights."
    )
    .unwrap();
    writeln!(
        out,
        "/// E.g. \"lord kri\" → \"The Bug Family\". Sorted for binary search."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static BOSS_TO_ENCOUNTER: &[(&str, &str)] = &["
    )
    .unwrap();
    for (boss, encounter) in &boss_to_encounter {
        writeln!(out, "    ({}, {}),", quote(boss), quote(encounter)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Raid encounter counts (sorted)
    writeln!(
        out,
        "/// Raid name → encounter count, sorted for binary search."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static RAID_ENCOUNTER_COUNTS: &[(&str, usize)] = &["
    )
    .unwrap();
    for (raid, count) in &raid_encounter_counts {
        writeln!(out, "    ({}, {count}),", quote(raid)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Zone aliases (sorted)
    writeln!(
        out,
        "/// Zone name aliases: addon-reported name → canonical raid name."
    )
    .unwrap();
    writeln!(out, "pub(crate) static ZONE_ALIASES: &[(&str, &str)] = &[").unwrap();
    for (alias, canonical) in &zone_aliases {
        writeln!(out, "    ({}, {}),", quote(alias), quote(canonical)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Overworld zones (sorted)
    writeln!(
        out,
        "/// Non-raid overworld zones that should never be treated as raid instances."
    )
    .unwrap();
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "pub(crate) static OVERWORLD_ZONES: &[&str] = &[").unwrap();
    for z in &overworld {
        writeln!(out, "    {},", quote(z)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // All instance names (sorted) — includes both raids and dungeons
    writeln!(
        out,
        "/// All canonical instance zone names (lowercased, sorted) for O(log n) lookup."
    )
    .unwrap();
    writeln!(out, "pub(crate) static ALL_RAID_ZONES: &[&str] = &[").unwrap();
    let mut raid_names: Vec<String> = db.raid.iter().map(|r| r.name.to_lowercase()).collect();
    raid_names.sort();
    for name in &raid_names {
        writeln!(out, "    {},", quote(name)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // Dungeon-only zones (sorted) — subset of ALL_RAID_ZONES where dungeon = true
    writeln!(
        out,
        "/// Dungeon zone names (5-man instances, sorted) for O(log n) lookup."
    )
    .unwrap();
    writeln!(out, "pub(crate) static DUNGEON_ZONES: &[&str] = &[").unwrap();
    let mut dungeon_names: Vec<String> = db
        .raid
        .iter()
        .filter(|r| r.dungeon)
        .map(|r| r.name.to_lowercase())
        .collect();
    dungeon_names.sort();
    for name in &dungeon_names {
        writeln!(out, "    {},", quote(name)).unwrap();
    }
    writeln!(out, "];").unwrap();

    eprintln!(
        "raid_data: {} NPCs ({} bosses, {} trash), {} raids, {} zone aliases",
        npc_to_raid.len(),
        boss_to_raid.len(),
        npc_to_raid.len() - boss_to_raid.len(),
        db.raid.len(),
        zone_aliases.len()
    );
}

// ── Consumable Data Codegen ──────────────────────────────────────────────────

#[derive(Deserialize)]
struct ConsumableDb {
    ignored: IgnoredItems,
    category: Vec<ConsumableCategory>,
}

#[derive(Deserialize)]
struct IgnoredItems {
    items: Vec<String>,
}

#[derive(Deserialize)]
struct ConsumableCategory {
    #[allow(dead_code)] // Deserialized for TOML structure validation; not used in codegen
    name: String,
    display: String,
    #[serde(default)]
    prefix: Option<String>,
    items: Vec<String>,
    /// Combat log buff names that differ from the item name.
    #[serde(default)]
    buff_names: Vec<String>,
    /// If true, buffs in this category persist through player death (Flasks, Zanzas).
    #[serde(default)]
    death_persistent: bool,
}

#[allow(clippy::too_many_lines)] // Code-generation — linear sequence of write! calls
fn generate_consumable_data() {
    println!("cargo:rerun-if-changed=data/consumables.toml");

    let toml_str =
        fs::read_to_string("data/consumables.toml").expect("failed to read data/consumables.toml");
    let db: ConsumableDb =
        toml::from_str(&toml_str).expect("failed to parse data/consumables.toml");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("consumable_data_generated.rs");
    let mut out = fs::File::create(&out_path).expect("failed to create consumable output file");

    // ── Ignored items (sorted for binary search) ────────────────────
    let mut ignored: Vec<String> = db.ignored.items;
    ignored.sort();

    writeln!(out, "// @generated by build.rs from data/consumables.toml").unwrap();
    writeln!(out, "// Do not edit manually.").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "/// Items in \"uses\" lines that are NOT consumables, sorted for binary search."
    )
    .unwrap();
    writeln!(out, "pub(crate) static IGNORED_ITEMS: &[&str] = &[").unwrap();
    for item in &ignored {
        writeln!(out, "    {},", quote(item)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // ── Item → category index (sorted by item name for binary search) ───
    let mut item_to_cat: Vec<(String, u8)> = Vec::new();
    for (cat_idx, cat) in db.category.iter().enumerate() {
        let idx = u8::try_from(cat_idx).expect("too many categories (max 255)");
        for item in &cat.items {
            item_to_cat.push((item.clone(), idx));
        }
    }
    item_to_cat.sort_by(|a, b| a.0.cmp(&b.0));

    writeln!(
        out,
        "/// Item name → category index, sorted by name for binary search."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static ITEM_TO_CATEGORY: &[(&str, u8)] = &["
    )
    .unwrap();
    for (item, idx) in &item_to_cat {
        writeln!(out, "    ({}, {idx}),", quote(item)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // ── Prefix patterns (e.g. "Scroll of " → Scroll category) ──────
    let mut prefixes: Vec<(String, u8)> = Vec::new();
    for (cat_idx, cat) in db.category.iter().enumerate() {
        if let Some(ref prefix) = cat.prefix {
            let idx = u8::try_from(cat_idx).expect("too many categories");
            prefixes.push((prefix.clone(), idx));
        }
    }

    writeln!(
        out,
        "/// Prefix patterns for fallback matching (e.g. \"Scroll of \" → Scroll category)."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static CATEGORY_PREFIXES: &[(&str, u8)] = &["
    )
    .unwrap();
    for (prefix, idx) in &prefixes {
        writeln!(out, "    ({}, {idx}),", quote(prefix)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // ── Category display names (indexed by category u8) ─────────────
    writeln!(
        out,
        "/// Display names for each category, indexed by category u8."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static CATEGORY_DISPLAY_NAMES: &[&str] = &["
    )
    .unwrap();
    for cat in &db.category {
        writeln!(out, "    {},", quote(&cat.display)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // ── Buff name → category index (for aura names that differ from item names)
    let mut buff_to_cat: Vec<(String, u8)> = Vec::new();
    for (cat_idx, cat) in db.category.iter().enumerate() {
        let idx = u8::try_from(cat_idx).expect("too many categories (max 255)");
        for buff_name in &cat.buff_names {
            buff_to_cat.push((buff_name.clone(), idx));
        }
    }
    buff_to_cat.sort_by(|a, b| a.0.cmp(&b.0));

    writeln!(
        out,
        "/// Buff names that differ from item names → category index, sorted for binary search."
    )
    .unwrap();
    writeln!(
        out,
        "/// Used to associate aura intervals with consumable categories on the timeline."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static BUFF_TO_CATEGORY: &[(&str, u8)] = &["
    )
    .unwrap();
    for (buff, idx) in &buff_to_cat {
        writeln!(out, "    ({}, {idx}),", quote(buff)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // ── Death-persistent category indices ───────────────────────────
    let death_persistent_cats: Vec<u8> = db
        .category
        .iter()
        .enumerate()
        .filter(|(_, cat)| cat.death_persistent)
        .map(|(idx, _)| u8::try_from(idx).expect("too many categories"))
        .collect();

    writeln!(
        out,
        "/// Category indices for buffs that persist through player death."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) static DEATH_PERSISTENT_CATEGORIES: &[u8] = &[{}];",
        death_persistent_cats
            .iter()
            .map(std::string::ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();

    let total_items: usize = item_to_cat.len();
    let total_buffs: usize = buff_to_cat.len();
    eprintln!(
        "consumable_data: {} items across {} categories, {} ignored, {} prefixes, {} buff overrides",
        total_items,
        db.category.len(),
        ignored.len(),
        prefixes.len(),
        total_buffs
    );
}

/// Quote a string as a Rust string literal.
fn quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}
